// Regenerate native reference data directly from the Web client's TypeScript constants.
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const ts = require('../../node_modules/typescript');
const root = path.resolve(__dirname, '../..');
const cache = new Map();
function readModule(filename) {
  filename = path.resolve(filename);
  if (cache.has(filename)) return cache.get(filename);
  const exports = {};
  cache.set(filename, exports);
  const source = ts.transpileModule(fs.readFileSync(filename, 'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022 } }).outputText;
  vm.runInNewContext(source, {exports, require: name => readModule(name.startsWith('@/') ? path.join(root, 'src', name.slice(2)) : path.resolve(path.dirname(filename), name))}, {filename});
  return exports;
}
const out = path.join(root, 'flutter_app/assets/reference');
fs.mkdirSync(out, {recursive:true});
function write(name, value) { fs.writeFileSync(path.join(out, name + '.json'), JSON.stringify(value, null, 2) + '\n'); }
const categories = readModule(path.join(root, 'src/consts/category.ts'));
write('category_presets', {'1':categories.DEFAULT_INCOME_CATEGORIES,'2':categories.DEFAULT_EXPENSE_CATEGORIES,'3':categories.DEFAULT_TRANSFER_CATEGORIES});
const currencies = readModule(path.join(root,'src/consts/currency.ts')).ALL_CURRENCIES;
write('currencies', Object.values(currencies).map(item => ({...item,name:item.unit})));
const iconData = readModule(path.join(root,'src/consts/icon.ts'));
const css = fs.readFileSync(path.join(root,'node_modules/line-awesome/dist/line-awesome/css/line-awesome.css'),'utf8');
const glyphs = {};
for (const match of css.matchAll(/\.la-([\w-]+):before\s*\{\s*content:\s*"\\([0-9a-f]+)"/g)) glyphs[match[1]] = parseInt(match[2],16);
const icons = {};
for (const [kind, source] of Object.entries({account:iconData.ALL_ACCOUNT_ICONS,category:iconData.ALL_CATEGORY_ICONS})) {
  icons[kind] = Object.entries(source).map(([id,item]) => {
    const name = item.icon.split(' ').find(value=>value.startsWith('la-')).slice(3);
    return {id, name:name.replaceAll('-',' '), css:item.icon, codePoint:glyphs[name], fontFamily:item.icon.startsWith('lab')?'LineAwesomeBrands':item.icon.startsWith('lar')?'LineAwesomeRegular':'LineAwesomeSolid'};
  });
}
write('icons',icons);
const dart = ['// Generated by tool/generate_reference_assets.cjs. Do not edit by hand.',"import 'package:flutter/widgets.dart';",'const referenceIcons = <String, Map<String, IconData>>{'];
for (const [kind, values] of Object.entries(icons)) {
  dart.push(`  '${kind}': {`);
  for (const item of values) {
    if (!item.codePoint) throw new Error(`Missing icon glyph ${kind}/${item.id}: ${item.css}`);
    dart.push(`    '${item.id}': IconData(${item.codePoint}, fontFamily: '${item.fontFamily}'),`);
  }
  dart.push('  },');
}
dart.push('};','');
fs.writeFileSync(path.join(root,'flutter_app/lib/ui/reference_icons.dart'),dart.join('\n'));
const fonts = path.join(root,'flutter_app/assets/fonts');
fs.mkdirSync(fonts,{recursive:true});
for (const font of ['la-solid-900.ttf','la-regular-400.ttf','la-brands-400.ttf']) fs.copyFileSync(path.join(root,'node_modules/line-awesome/dist/line-awesome/fonts',font),path.join(fonts,font));
const overview = readModule(path.join(root,'src/consts/overview_layout.ts'));
write('overview_widgets',overview.MOBILE_OVERVIEW_WIDGET_DEFINITIONS);
write('overview_default',overview.DEFAULT_MOBILE_OVERVIEW_LAYOUT);
console.log(`Generated ${Object.values(icons).flat().length} icons, ${Object.keys(currencies).length} currencies, ${Object.keys(overview.MOBILE_OVERVIEW_WIDGET_DEFINITIONS).length} mobile widget definitions.`);
